### ISSUE TITLE
Studiengangsbeschreibungen

### ISSUE THREAD

**Issue by flugdrachen** [FachschaftMathPhysInfo/Ersti-Info#234]
Die Beschreibungen der verschiedenen Studiengänge sind sehr uneinheitlich in ihrer Ausführlichkeit. Es stehen viele Dinge in den einzelnen Beschreibungen, die eigentlich besser in den allgemeinen Teil passen würden. Das sollte man mal überarbeiten.

**Comment by OccamsBeard** [comment]
Ziele:
* maximal zwei Seiten pro Studiengang
* Informationen, die in den allgemeinen Teil können, dorthin auslagern
* Nach Möglichkeit graphische Darstellungen für Informationen finden
* Ggf. mehr verweisen (z.B. auf andere Abschnitte oder komplett andereQuellen)

**Comment by flugdrachen** [comment]
für den allgemeinen Teil und für Informatik erledigt via #266 - es fehlen Mathe und Physik.

**Comment by mathivierpunktnull** [comment]
Das wäre doch was für das nächste FSWE.
