### ISSUE TITLE
"zu aktualisierendes" erweitern

### ISSUE THREAD

**Issue by koebi** [FachschaftMathPhysInfo/Ersti-Info#32]
Viele Dinge gehören auch ständig aktualisiert und deswegen ins zu aktualisierende.
Das sind unter anderem die Öffnungszeiten der Bib und die Daten aus den vorkursplänen (um die Texte da rauszunehmen).

**Comment by TomTomRixRix** [comment]
Die Daten wurden 2021 aktualisiert. Es gibt allerdings einige commands, die nicht mehr verwendet werden.

Weiterhin müsste man aber einmal durch das ganze Ersti-Info gehen und schauen, was Daten sind, die sich aktualisieren und diese dann refactor'n.
