### ISSUE TITLE
Informationen für Transpersonen aufnehemen

### ISSUE THREAD

**Issue by EinHerzfuerSci-Fi** [FachschaftMathPhysInfo/Ersti-Info#372]
- Dies könnte eine Information über einen möglichen Leitfaden sein.
- Und ggf. zusätztlich darüber aufklären, dass man in der Übungsgruppenverwaltung seinen namen ändern lassen kann.
- es könnte auch auf den Discord Server hingewiesen werden.

**Comment by mathivierpunktnull** [comment]
Erste Infos hat der AK-Queer schon mal hier zusammengetragen:
https://mathphys.stura.uni-heidelberg.de/w/informationen-fuer-lgbtq%c2%b1studierende/

**Comment by TomTomRixRix** [comment]
Hey ihr beiden,

ich fände es cool, wenn wir in der nächsten Ausgabe des Ersti-Infos schon mal etwas zu diesem Thema aufnehmen. Es muss ja kein ganzer Leitfanden und in keiner Weise vollständig sein, aber man kann ja einfach drauf hinweisen, dass es Angebote gibt und man nicht alleine ist.

Wollt ihr vielleicht einfach mal einen kleinen Text schreiben? Und hättet ihr einen Vorschlag, wo im Ersti-Info man den am geschicktesten einfügt? Spontan hätte ich gesagt, dass es zu den anderen Angeboten wie Zentraler Studienberatung, Career Service und Nightline vielleicht am ehesten passt. Allerdings sind in dem Kapitel auch Studieren mit Handicap und Kummerkasten, was schon wieder weniger passt. Insgesamt heißt das Kapitel auch "Was tun bei Problemen?", da würde ich ungern die Assoziation erwecken wollen, dass Transpersonen per se Probleme hätten. Alternativ würden die beiden Kapitel "An der Uni..." und "...in der Stadt" vielleicht auch noch passen.

**Comment by TomTomRixRix** [comment]
Dieses Issue scheint dann ja jetzt erledigt zu sein 💪
