### ISSUE TITLE
ÖPNV Angebote aktualisieren?

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhysInfo/Ersti-Info#407]
Je nachdem wie die Verhandlungen ausgehen und sich die Situation mit dem Semesterticket, dem 9€ Ticket Nachfolger und dem 365€ Ticket weiterentwickelt, müssten unsere Texte angepasst werden. Mehr Hintergründe auf der [StuRa-Webseite](https://www.stura.uni-heidelberg.de/2022/10/12/neun-euro-ticket/).

Dementsprechend müsste man vermutlich auch die Semesterbeitragsgrafik (vgl. #354) und die Zahlen anpassen.

**Comment by Splines** [comment]
Text bezüglich Verkehrsmittel geupdated in #421. Semesterbeitragsgrafik geupdated in #432.
