### ISSUE TITLE
Marsilius Studien erwähnen

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhysInfo/Ersti-Info#409]
Wir könnten das coole interdisziplinäre Angebot des Marsilius Kollegs bewerben: https://www.marsilius-kolleg.uni-heidelberg.de/studien/index.html 

Teilweise lassen sich die Brückenseminare sogar in unseren Fächern anrechnen.

**Comment by TomTomRixRix** [comment]
@Lucius1274 Wurde ein Text zu den Marsilius Studien hinzugefügt oder warum wurde das Issue geschlossen?

**Comment by Lucius1274** [comment]
@TomTomRixRix hab die issues erst mal temporär geschlossen um einen Überblick zu behalten, aber die Marsilius-Studien sind auf jeden Fall erwähnenswert, deswegen reopene ich das issue wieder

**Comment by TomTomRixRix** [comment]
Ah ok, ich war nur verwundert, dass einige Issues kommentarlos geschlossen wurden. Vielleicht kann man über labels oder Meilensteine für etwas mehr Überblick sorgen.
