### ISSUE TITLE
heiCO

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhysInfo/Ersti-Info#410]
Mit dem Wechsel auf campus online muss vielleicht einiges im Ersti Info angepasst werden. Momentan vermutlich erstmal nur für Anwendungsgebiete, aber langfristig vielleicht auch für unsere Fächer, das sollte man mal überprüfen

**Comment by Splines** [comment]
I mentioned the use case of heiCO in #414.
