### ISSUE TITLE
Infos zum Kummerkasten entfernen

### ISSUE THREAD

**Issue by lennart-r** [FachschaftMathPhysInfo/Ersti-Info#423]
Der Kummerkasten funktioniert momentan nicht. Entweder sollte er wieder zum Laufen gebracht werden, oder man nimmt das Kapitel zum Kummerkasten, sowie den Verweis auf den Kummerkasten bei der Lehrevaluation raus (vielleicht mal nur auskommentieren, damit man es schnell wieder hat, sollte der Kummerkasten mal wieder zum Laufen gebracht werden).

**Comment by Splines** [comment]
Der Kummerkasten funktioniert momentan zumindest aus technischer Sicht (nach meinem letzten Stand in der Sitzung, in der ich das @christian-heusel gefragt habe), es müsste sich nur eine Person finden, die die aktuellen Vorlesungen dort einträgt.

Glaubst du ich soll das dann wirklich komplett rausnehmen oder wenigstens darauf hinweisen, dass es den Kummerkasten gibt? 

@christian-heusel, vlt. könntest du einen kleinen Hinweis auf der Kummerkasten-Website schreiben, dass zurzeit die Vorlesungen nicht eingetragen sind?

**Comment by christian-heusel** [comment]
Ja genau, der stand der den @lennart-r beschrieben hat stimmt leider, es kümmert sich einfach niemand 🤔 😢 
Meiner Meinung nach sollte man das jetzt entfernen, damit die Leute sich nicht auf einen aktuell disfunktionalen Dienst verlassen ...

Wenn es ansonsten aber nicht abgedeckt ist wäre das ja vielleicht mal ne gute Stelle um zu sagen, dass sich die Fachschaft allgemeiner Kritik an Lehrveranstaltungen annimmt 👍🏻

**Comment by Splines** [comment]
Danke euch für die schnelle Rückmeldung. Ich habe jetzt den Kummerkasten rausgenommen und bei der Lehrevaluation einen entsprechenden Hinweis hinzugefügt, dass wir auch Kritik an Lehrveranstaltungen annehmen, siehe #435.
