### ISSUE TITLE
Semesterticket

### ISSUE THREAD

**Issue by fschledorn** [FachschaftMathPhysInfo/Ersti-Info#428]
Habt ihr dran gedacht den Wegfall des Semestertickets zu aktualisieren. Im Text zu Semesterticket und den Semestergebühren sah das bisher noch nicht so aus. Aber vielleicht hab ich das aber auch einfach übersehen

**Comment by Splines** [comment]
@fschledorn Hey Felix, danke für die Erinnerung. Ja, ich habe gestern noch die Grafik für die Semestergebühren aktualisiert:

![image](https://github.com/FachschaftMathPhysInfo/Ersti-Info/assets/37160523/bc6610da-b503-4f20-8267-b0381849043c)


Den Text zum Semesterticket haben wir komplett überarbeitet, der Text ist jetzt unter "Verkehrsmittel Heidelberg":

> Seit Anfang des Jahres gibt es für alle unter 27 Jahren, die an einer Hochschule in BadenWürttemberg studieren, das sogenannte Jugendticket BW. [...]

**Comment by fschledorn** [comment]
Super, wollte nur sichergehen
